---
- hosts: all
  gather_facts: no
  tasks:
  - name: Get user authorization token
    uri:
      url: "{{ grid_admin_base_url }}api/v3/authorize"
      method: POST
      body: {
        "username": "{{ grid_user }}",
        "password": "{{ grid_pass }}",
        "cookie": false,
        "csrfToken": false
      }
      body_format: json
      validate_certs: false
    register: auth
    no_log: false
  - name: print auth token
    debug:
      msg: "{{ auth.json.data }}"

  - name: create a group
    netapp.storagegrid.nac_sg_org_group:
      api_url: "{{ grid_admin_base_url }}"
      auth_token: "{{ auth.json.data }}"
      validate_certs: false
      state: present
      #      display_name: ansiblegroup101
      #      unique_name: group/ansiblegroup101
      management_policy:
        manage_all_containers: true
        manage_endpoints: true
        manage_own_s3_credentials: false
        root_access: false
      s3_policy: {"Statement":[{"Effect":"Deny","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}
