---
- hosts: all
  gather_facts: no
  tasks:
  - name: Get user authorization token
    uri:
      url: "{{ grid_admin_base_url }}api/v3/authorize"
      method: POST
      body: {
        "accountId": "{{ account_id }}",
        "username": "{{ tenant_user }}",
        "password": "{{ tenant_pass }}",
        "cookie": false,
        "csrfToken": false
      }
      body_format: json
      validate_certs: false
    register: auth
    no_log: false

  - name: print auth token
    debug:
      msg: "{{ auth.json.data }}"

  - name: create a s3 key
    netapp.storagegrid.nac_sg_org_user_s3_key:
      api_url: "{{ grid_admin_base_url }}"
      auth_token: "{{ auth.json.data }}"
      validate_certs: false
      state: present
      unique_user_name: user/ansibleuser2
